# -*- coding: utf-8 -*-
"""nlp-app-reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gezl2lvpgG3dxf4mH_AabADDNm5cf_I2
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("prakharrathi25/google-play-store-reviews")

print("Path to dataset files:", path)

import os
import pandas as pd
DATASET_FILENAME= 'reviews.csv'
files = os.listdir(path)
print("Files in dataset: ", files)

df = pd.read_csv(os.path.join(path, DATASET_FILENAME))
# print(df.head(5))
print("Data size:\n", df.size)
print("Columns:\n", df.columns.to_list())
print("Total # rows:\n", len(df))
print("\nContents:\n", df['content'].head(5))
print("\nScores:\n", df['score'].head(5))
print("\nTime:\n", df['at'].head(5))

# Data CLeaning
import numpy as np
from sentence_transformers import SentenceTransformer
df_clean = df[['content', 'score', 'at']].copy()
df_clean.rename(columns={'content': 'review_text', 'score': 'rating', 'at': 'review_date'}, inplace=True)

# Convert all columns to string
df_clean['rating'] = df_clean['rating'].astype(str).str.strip()
df_clean['review_text'] = df_clean['review_text'].astype(str).str.strip()
df_clean['review_date'] = df_clean['review_date'].astype(str).str.strip()
print(df_clean.columns.to_list())

# Drop nulls
print("Before drop na: ", len(df_clean))
df_clean.dropna(inplace=True)
print("After drop na: ", len(df_clean))

# Drop duplicates
print("Before drop dup: ", len(df_clean))
df_clean.drop_duplicates(subset=['review_text'], inplace=True, keep='first')
print("After drop dup: ", len(df_clean))

# Generate Embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')
reviews_list = df_clean['review_text'].to_list()
embeddings = model.encode(reviews_list, batch_size=32, show_progress_bar=True, convert_to_numpy=True)
print("Embeddings shape: ", embeddings.shape) # returns tuple
print(f" - Rows (reviews): {embeddings.shape[0]}")
print(f"  - Columns (dimensions): {embeddings.shape[1]}")
print(f"  - Memory size: {embeddings.nbytes / 1024 / 1024:.1f} MB\n")

df_clean['embedding'] = [embedding.tolist() for embedding in embeddings]
print(f"df embedding: {df_clean['embedding'].head(5)}")

import sqlite3
import numpy as np

db_path = '/content/reviews.db'
conn = sqlite3.connect(db_path)

print(f"db path: {db_path}")

cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS reviews (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        review_text TEXT NOT NULL,
        rating TEXT,
        review_date TEXT,
        embedding BLOB
    )
''')

for index, row in df_clean.iterrows():
  # Convert embedding list to numpy then to bytes
  embedding_array = np.array(row['embedding'], dtype=np.float32)
  embedding_bytes = embedding_array.tobytes()

  cursor.execute('''
      INSERT INTO reviews (review_text, rating, review_date, embedding)
      VALUES (?, ?, ?, ?)
  ''', (
      row['review_text'],
      row['rating'],
      row['review_date'],
      embedding_bytes
  ))

# Show progress every 2000 rows
if (index + 1) % 2000 == 0:
    print(f"  ✓ {index + 1} / {len(df_clean)} reviews inserted")

conn.commit()

# Verify
cursor.execute("SELECT COUNT(*) FROM reviews")
total = cursor.fetchone()[0]
print(f"✓ Total reviews in database: {total}")

conn.close()

!pip install rank-bm25 -q

# Retrieval
from rank_bm25 import BM25Okapi

# Connect to db
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Get all reviews from db
cursor.execute("SELECT id, review_text, rating, review_date, embedding FROM reviews")
all_rows = cursor.fetchall()
# print(f"All rows: {all_rows}")
print(f"count={all_rows[0]}")

# Load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

review_ids = []
review_texts = []
review_ratings = []
review_dates = []
review_embeddings = []

for row in all_rows:
  review_ids.append(row[0])
  review_texts.append(row[1])
  review_ratings.append(row[2])
  review_dates.append(row[3])

  embedding_bytes = row[4]
  embedding_array = np.frombuffer(embedding_bytes, dtype=np.float32)
  review_embeddings.append(embedding_array) # Got list of arrays

# Convert list of arrays to 2D numpy array
review_embeddings = np.array(review_embeddings)
print(f"Reviews embeddings shape: {review_embeddings.shape}")

# Prepare BM25
tokenized_reviews = [review.lower().split() for review in review_texts]

# Create BM25 ranker
bm25 = BM25Okapi(tokenized_reviews)

def retrieve_reviews(query, top_k=5):
  print(f"Query: {query}")

  # BM25 search (keyword matching)
  query_tokens = query.lower().split()
  bm25_scores = bm25.get_scores(query_tokens)
  print(f"BM25 scored: {bm25_scores}")

  # Convert query into embeddings
  query_embedding = model.encode(query, convert_to_numpy=True)
  # print(f"Query embedding: {query_embedding}")

  # Get magnitude
  query_norm = np.linalg.norm(query_embedding)
  reviews_norm = np.linalg.norm(review_embeddings, axis=1)
  print(f"Query norm: {query_norm}")
  print(f"Reviews norm: {reviews_norm}, shape={reviews_norm.shape}")

  # Calculate cosine similarity
  # Cosine similarity = dot product / (norm1 * norm2)
  dot_product = np.dot(review_embeddings, query_embedding)
  cosine_similarities = dot_product / (query_norm * reviews_norm)
  print(f"Dot product: {dot_product}")
  print(f"Cosine similarities: {cosine_similarities}")

  # Normalize
  normalized_cosine_sim = (cosine_similarities + 1) / 2
  print(f"Normalized cosine similarities: {normalized_cosine_sim}")

  max_bm25 = np.max(bm25_scores)
  if max_bm25 > 0:
    bm25_normalized = bm25_scores / max_bm25
  else:
    bm25_normalized = bm25_scores

  combined_scores = bm25_scores * 0.4 + normalized_cosine_sim * 0.6

  # Rank them by scores, return indicess
  top_indices = np.argsort(combined_scores)[::-1][:top_k]

  for rank, index in enumerate(top_indices):
    print(f"\n[Rank {rank}] Review ID: {review_ids[index]}")
    print(f"  Rating: {review_ratings[index]}⭐")
    print(f"  Date: {review_dates[index]}")
    print(f"  BM25 Score: {bm25_normalized[index]:.3f}")
    print(f"  Cosine Similarity Score: {normalized_cosine_sim[index]:.3f}")
    print(f"  Combined Score: {combined_scores[index]:.3f}")
    print(f"  Text: {review_texts[index][:100]}...")

  return top_indices

def get_review_details(indices):
  reviews_for_llm = []
  for index in indices:
    review_dict = {
        "id": review_ids[index],
        "rating": review_ratings[index],
        "date": review_dates[index],
        "text": review_texts[index]
        }
    reviews_for_llm.append(review_dict)
  return reviews_for_llm


query2 = "app frozen"
results2 = retrieve_reviews(query2, top_k=5)

!pip install transformers bitsandbytes accelerate -q

# LLM integration
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
llm_model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
# llm_model_name = "mistralai/Mistral-7B-Instruct-v0.1"
tokenizer = AutoTokenizer.from_pretrained(llm_model_name)

# Configure 4-bit quantization
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

llm_model = AutoModelForCausalLM.from_pretrained(llm_model_name, device_map="auto", quantization_config=bnb_config, torch_dtype=torch.float16)


def generate_answer_with_citations(query, top_reviews, max_tokens=256):
  reviews_text = ""
  for review in top_reviews:
    reviews_text += f"Review # {review['id']}, Rating: {review['rating']}, Review: {review['text']}"

  system_prompt = """You are a helpful assistant analyzing app reviews.
  Your job is to answer questions about reviews using ONLY the retrieved reviews below.

  IMPORTANT RULES:
  1. Always cite reviews using format [Review #ID]
  2. Never make up information not in the reviews
  3. Be concise (2-3 sentences max)
  4. If you don't know, say "I don't have enough information"

  Retrieved Reviews:
  """ + reviews_text

  user_message = f"Question: {query}\n\nAnswer (cite reviews): "
  prompt = system_prompt + user_message

  input = tokenizer(prompt, return_tensors="pt").to("cuda")
  print(f"Input tokens: {input['input_ids'].shape[1]}")

  output = llm_model.generate(
      input['input_ids'],
      max_new_tokens=max_tokens,
      temperature=0.7,
      top_p=0.9,
      do_sample=True
  )

  response_text = tokenizer.decode(output[0], skip_special_tokens=True)
  print(f"Response: {response_text}")
  answer = response_text.split("Answer (cite reviews):")[-1].strip()
  print(f"Answer: {answer}")
  return answer

print("="*80)
print("TESTING: RETRIEVAL + LLM")
print("="*80)

model_name = "mistralai/Mistral-7B-Instruct-v0.1"

# Step 1: Retrieve reviews
query = "app frozen"
print(f"\nQuery: '{query}'")

top_indices = retrieve_reviews(query, top_k=5)

# Step 2: Convert indices to review data
print(f"\nConverting {len(top_indices)} indices to review data...")
top_reviews = get_review_details(top_indices)

print(f"✓ Got {len(top_reviews)} reviews for LLM\n")

# Step 3: Show what we're sending to LLM
print("Reviews being sent to LLM:")
for review in top_reviews:
    print(f"  - Review #{review['id']}: {review['text'][:60]}...")

# Step 4: Generate answer with LLM
print(f"\n[LLM] Generating answer...\n")
answer = generate_answer_with_citations(query, top_reviews)

print(f"\n✓ FINAL ANSWER:\n{answer}")

from sentence_transformers import SentenceTransformer
import os

import os
import pickle
import numpy as np

print("Re-saving all models with current Colab versions...\n")

# Save embedding model
print("[1] Saving embedding model...")
model.save('/content/saved_models/embedding_model')
print("✓ Done")

# Save BM25
print("[2] Saving BM25...")
with open('/content/saved_models/bm25.pkl', 'wb') as f:
    pickle.dump(bm25, f)
print("✓ Done")

# Save tokenizer
print("[3] Saving tokenizer...")
tokenizer.save_pretrained('/content/saved_models/tokenizer')
print("✓ Done")

# Save LLM
print("[4] Saving LLM model...")
llm_model.save_pretrained('/content/saved_models/llm_model')
print("✓ Done")

# Save review data
print("[5] Saving review data...")
review_data = {
    'review_ids': review_ids,
    'review_texts': review_texts,
    'review_ratings': review_ratings,
    'review_dates': review_dates,
    'review_embeddings': review_embeddings
}
with open('/content/saved_models/review_data.pkl', 'wb') as f:
    pickle.dump(review_data, f)
print("✓ Done")

print("\n✓ ALL MODELS RE-SAVED with current Colab versions!")

print("Re-saving embedding model correctly...")

# Load fresh model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

# Save it correctly
save_path = '/content/saved_models/embedding_model'
os.makedirs(save_path, exist_ok=True)

embedding_model.save(save_path)

print(f"✓ Embedding model saved to {save_path}")

# Verify it has the right files
import os
files = os.listdir(save_path)
print(f"\nFiles in embedding_model/: {files}")

from google.colab import drive
import shutil

drive.mount('/content/gdrive')
shutil.copytree('/content/saved_models', '/content/gdrive/My Drive/saved_models', dirs_exist_ok=True)
print("✓ Copied to Google Drive - download from there!")

import re

print("="*80)
print("PHASE 3 STEP 3: Extract Citations with Regex")
print("="*80)

def extract_citations(text):
    """
    Extract all [Review #XXXX] citations from text using regex

    Args:
        text: LLM response with citations

    Returns:
        List of review IDs found in citations
    """

    # Regex pattern: [Review #123]
    # \[ = literal [
    # Review # = literal text
    # (\d+) = capture one or more digits
    # \] = literal ]
    pattern = r'\[Review #(\d+)\]'

    # Find all matches
    matches = re.findall(pattern, text)

    # Convert to integers
    citation_ids = [int(m) for m in matches]

    return citation_ids

# Test it
test_answer = """[Review #7501] and [Review #10989] mention that the app freezes.
[Review #4033] also reports the app is not responding."""

print(f"\nTest answer:\n{test_answer}\n")

citations = extract_citations(test_answer)
print(f"Extracted citations: {citations}")
print(f"Total citations found: {len(citations)}")

# Show review details for each citation
print("\nCitation Details:")
for citation_id in citations:
    # Find the review in our database
    idx = review_ids.index(citation_id)
    print(f"\n  [Review #{citation_id}]")
    print(f"    Rating: {review_ratings[idx]}⭐")
    print(f"    Date: {review_dates[idx]}")
    print(f"    Text: {review_texts[idx][:80]}...")

print("\n" + "="*80)
print("✓ STEP 3 COMPLETE - Citations can be extracted!")
print("="*80)

import pickle
import numpy as np
from sklearn.cluster import KMeans
from collections import defaultdict

print("Loading review data...\n")

with open('/content/saved_models/review_data.pkl', 'rb') as f:
    review_data = pickle.load(f)

review_ids = review_data['review_ids']
review_texts = review_data['review_texts']
review_ratings = review_data['review_ratings']
review_dates = review_data['review_dates']
review_embeddings = review_data['review_embeddings']

print(f"Loaded {len(review_ids)} reviews")

# Load existing clusters (don't re-run KMeans)
with open('/content/saved_models/review_clusters.pkl', 'rb') as f:
    cluster_data = pickle.load(f)

clusters = cluster_data['clusters']
kmeans = cluster_data['kmeans_model']
n_clusters = cluster_data['n_clusters']

print("\n" + "="*80)
print("ASSIGNING BETTER TOPIC NAMES")
print("="*80)

cluster_names = {}

# Keywords for each topic - check in order
topic_keywords = {
    'Crashes & Freezing': ['crash', 'freeze', 'frozen', 'not responding', 'force close', 'stopped', 'bug'],
    'Battery & Power': ['battery', 'drain', 'power', 'consumption', 'charge'],
    'GPS & Navigation': ['gps', 'location', 'navigation', 'directions', 'maps'],
    'UI & Design': ['ui', 'interface', 'design', 'layout', 'icons', 'usability', 'widget'],
    'Performance': ['slow', 'lag', 'speed', 'fast', 'quick'],
    'Offline Mode': ['offline', 'download', 'internet', 'connection'],
    'Premium & Pricing': ['premium', 'price', 'cost', 'refund', 'paid', 'free'],
    'Features & Functionality': ['feature', 'function', 'sync', 'calendar', 'task', 'list']
}

for cluster_id in range(n_clusters):
    reviews = clusters[cluster_id]
    avg_rating = np.mean([float(r['rating']) for r in reviews])

    print(f"\nCLUSTER {cluster_id}: {len(reviews)} reviews (avg rating: {avg_rating:.1f}⭐)")

    # Get all text from this cluster
    cluster_text = ' '.join([r['text'].lower() for r in reviews])

    # Find BEST matching topic
    best_topic = "Other Issues"
    best_score = 0

    for topic, keywords in topic_keywords.items():
        score = sum(cluster_text.count(keyword) for keyword in keywords)

        if score > best_score:
            best_score = score
            best_topic = topic

    cluster_names[cluster_id] = best_topic

    # Show sample
    print(f"  Sample: {reviews[0]['text'][:80]}...")
    print(f"  → {best_topic} (score: {best_score})")

# Save updated clusters
cluster_data['cluster_names'] = cluster_names

with open('/content/saved_models/review_clusters.pkl', 'wb') as f:
    pickle.dump(cluster_data, f)

# Print final summary
print("\n" + "="*80)
print("FINAL TOPIC BREAKDOWN")
print("="*80)

for cluster_id in range(n_clusters):
    reviews = clusters[cluster_id]
    avg_rating = np.mean([float(r['rating']) for r in reviews])
    print(f"{cluster_names[cluster_id]}: {len(reviews)} reviews ({avg_rating:.1f}⭐)")

print("\n✓ Topics assigned correctly!")

import pickle
import numpy as np
from sklearn.cluster import KMeans
from collections import defaultdict

print("Loading review data...\n")

with open('/content/saved_models/review_data.pkl', 'rb') as f:
    review_data = pickle.load(f)

review_ids = review_data['review_ids']
review_texts = review_data['review_texts']
review_ratings = review_data['review_ratings']
review_dates = review_data['review_dates']
review_embeddings = review_data['review_embeddings']

print(f"Loaded {len(review_ids)} reviews\n")

# Run KMeans
print("Running KMeans clustering...\n")

n_clusters = 6
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10, verbose=1)
cluster_labels = kmeans.fit_predict(review_embeddings)

print("\n✓ Clustering complete!\n")

# Group by cluster
clusters = defaultdict(list)

for idx, label in enumerate(cluster_labels):
    clusters[label].append({
        'id': review_ids[idx],
        'text': review_texts[idx],
        'rating': review_ratings[idx],
        'date': review_dates[idx],
        'index': idx
    })

# Check in ORDER - first match wins
topics_ordered = [
    ('battery', ['battery', 'drain', 'power', 'charge']),
    ('gps', ['gps', 'location', 'navigation', 'maps', 'directions']),
    ('offline', ['offline', 'download', 'sync']),
    ('performance', ['slow', 'lag', 'hangs']),
    ('ui', ['widget', 'icon', 'layout', 'design']),
    ('crashes', ['freeze', 'frozen', 'force close', 'not responding'])
]

print("="*80)
print("ASSIGNING TOPICS TO CLUSTERS (KMeans + Priority Keywords)")
print("="*80)

cluster_to_topic = {}

# For each cluster, find FIRST matching topic
for cluster_id in range(n_clusters):
    reviews = clusters[cluster_id]
    avg_rating = np.mean([float(r['rating']) for r in reviews])
    cluster_text = ' '.join([r['text'].lower() for r in reviews])

    print(f"\nCLUSTER {cluster_id}: {len(reviews)} reviews (avg rating: {avg_rating:.1f}⭐)")
    print(f"  Sample: {reviews[0]['text'][:80]}...")

    # Find FIRST matching topic
    found = False
    for topic_name, keywords in topics_ordered:
        if any(keyword in cluster_text for keyword in keywords):
            cluster_to_topic[cluster_id] = topic_name
            print(f"  → {topic_name.upper()}")
            found = True
            break

    if not found:
        cluster_to_topic[cluster_id] = 'other'
        print(f"  → OTHER")

# Save everything
print("\n" + "="*80)
print("Saving cluster + topic data...\n")

cluster_topic_data = {
    'clusters': clusters,
    'cluster_to_topic': cluster_to_topic,
    'topics_ordered': topics_ordered,
    'kmeans_model': kmeans,
    'n_clusters': n_clusters,
    'review_ids': review_ids,
    'review_texts': review_texts,
    'review_ratings': review_ratings,
    'review_dates': review_dates,
    'review_embeddings': review_embeddings
}

with open('/content/saved_models/cluster_topic_data.pkl', 'wb') as f:
    pickle.dump(cluster_topic_data, f)

print("✓ Saved to cluster_topic_data.pkl\n")

# Print final summary
print("="*80)
print("FINAL TOPIC BREAKDOWN")
print("="*80)

topic_summary = defaultdict(lambda: {'reviews': 0, 'avg_rating': []})

for cluster_id in range(n_clusters):
    reviews = clusters[cluster_id]
    topic = cluster_to_topic[cluster_id]
    ratings = [float(r['rating']) for r in reviews]
    avg_rating = np.mean(ratings)

    topic_summary[topic]['reviews'] += len(reviews)
    topic_summary[topic]['avg_rating'].extend(ratings)

for topic in sorted(topic_summary.keys()):
    data = topic_summary[topic]
    final_avg = np.mean(data['avg_rating'])
    print(f"{topic.upper()}: {data['reviews']} reviews ({final_avg:.1f}⭐)")

print("\n✓ Hybrid KMeans + Keyword clustering complete!")
print("✓ Ready for topic-based QA!")

# Test if models can load at all
import sys
sys.path.insert(0, '/content')

print("Testing model loading...\n")

try:
    print("[1] Loading embedding model...")
    from sentence_transformers import SentenceTransformer
    embedding_model = SentenceTransformer('./saved_models/embedding_model')
    print("✓ Embedding model loaded\n")

    print("[2] Loading BM25...")
    import pickle
    with open('./saved_models/bm25.pkl', 'rb') as f:
        bm25 = pickle.load(f)
    print("✓ BM25 loaded\n")

    print("[3] Loading tokenizer...")
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained('./saved_models/tokenizer')
    print("✓ Tokenizer loaded\n")

    print("[4] Loading LLM...")
    from transformers import AutoModelForCausalLM
    llm_model = AutoModelForCausalLM.from_pretrained('./saved_models/llm_model')
    print("✓ LLM loaded\n")

    print("[5] Loading review data...")
    with open('./saved_models/review_data.pkl', 'rb') as f:
        review_data = pickle.load(f)
    print("✓ Review data loaded\n")

    print("="*80)
    print("✓ ALL MODELS LOAD SUCCESSFULLY!")
    print("="*80)

except Exception as e:
    print(f"✗ ERROR: {str(e)}")
    import traceback
    traceback.print_exc()

!pip install streamlit -q

!streamlit run app.py --server.port=8501 --logger.level=error &
import time
time.sleep(10)
print("✓ Streamlit started")

from google.colab.output import eval_js
print(eval_js('google.colab.kernel.proxyPort(8501)'))